version: '3.8'

services:
  app:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/homedocs?schema=public
      - NEXTAUTH_URL=https://your-production-domain.com # Change this
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET} # Set this in production
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Set this in production
      - POSTGRES_DB=homedocs
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_prod: 