services:
  app:
    image: ghcr.io/homedocs-cc/homedocs:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - backups_prod:/app/backups
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_prod:
  backups_prod:
