# Generated by Django 5.0 on 2023-12-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_coating_location_remove_coating_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coating',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
