# Generated by Django 5.0 on 2023-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_coating_date_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coating',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
