# Generated by Django 5.0 on 2023-12-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_location_name_alter_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='coating',
            name='user',
            field=models.ForeignKey(default="a17277e30e774c67b931151e63f2fa91", on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
    ]
