# Generated by Django 5.0 on 2023-12-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_location_user_alter_item_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coatings',
            field=models.ManyToManyField(null=True, to='core.coating'),
        ),
        migrations.AlterField(
            model_name='room',
            name='coatings',
            field=models.ManyToManyField(null=True, to='core.coating'),
        ),
    ]
