# Generated by Django 5.0 on 2024-01-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_location_coatings_alter_room_coatings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='location_img'),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='image',
            field=models.ImageField(upload_to='room_img/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_img'),
        ),
    ]
