# Generated by Django 5.0 on 2024-01-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_location_image_alter_roomphoto_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/static/img/item-default.jpg', upload_to='item_img'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default='/static/img/location-default.jpg', upload_to='location_img'),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='image',
            field=models.ImageField(upload_to='room_img'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/img/avatar-default.jpg', upload_to='profile_img'),
        ),
    ]
