# Generated by Django 5.0 on 2024-01-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0020_alter_item_image_alter_item_name_alter_item_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owners',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_scheduled',
            field=models.DateTimeField(blank=True),
        ),
    ]
